version: '3'

services:
  app:
    build:
      context: .
    mem_limit: 4000m
    environment:
      DB_HOST: database
    ports:
      - 8080:8080

  postgres:
    image: postgres:14.3
    environment:
      - POSTGRES_DB=user
      - POSTGRES_PASSWORD=password

volumes:
  db-volume: null
